import Head from "next/head";
import Image from "next/image";
import Styles from "./about.module.css";
import { Button, Grid, Box, Typography } from "@mui/material";
import { FiArrowRightCircle } from "react-icons/fi";
import Navbar from "../components/Navbar";
import About from "../components/About";
import Services from "../components/Services";
import Project from "../components/Project";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Owl from "../components/Owl";
import Banner1Img from "../public/home/banner/3.jpg";
import { red } from "@mui/material/colors";
import { styled } from "@mui/system";

const StyledBox = styled(Box)`
  position: absolute;
  top: 30%;
  left: 10%;
`;

export default function Home() {
  return (
    <>
      <div className={Styles.banner}>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Navbar />
          <StyledBox component="div">
            <Typography
              variant="h4"
              sx={{ flexgrow: 1 }}
              style={{ color: "white" }}
            >
              I'm ......
            </Typography>
            <Typography
              variant="p"
              component="p"
              sx={{ flexgrow: 1 }}
              style={{ color: "white" }}
            >
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry.Lorem Ipsum is simply dummy text of the printing and
              typesetting industry.
            </Typography>
            <Button
              variant="contained"
              color="success"
              style={{ marginTop: "10px" }}
            >
              Download
            </Button>
          </StyledBox>
        </main>
      </div>
      <About />
      <Services />
      <Project />
      <Contact />
      <Footer />
      <Owl />
    </>
  );
}
